apiVersion: batch/v1
kind: Job
metadata:
  name: alpakka-kafka-publisher-1-million
spec:
  template:
    # This is the pod template
    spec:
      containers:
        - name: alpakka-kafka-publisher-1-million
          image: miguelemos/alpakka_kafka_publisher:amd64
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_SERVERS
              value: "my-kafka.default.svc.cluster.local:9092"
      restartPolicy: OnFailure
      # The pod template ends here