---
apiVersion: batch/v1
kind: Job
metadata:
  name: alpakka-kafka-publisher-1-million
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: alpakka
  template:
    metadata:
      labels:
        app: alpakka
    # This is the pod template
    spec:
      containers:
        - name: alpakka-kafka-publisher-1-million
          image: miguelemos/alpakka_kafka_publisher:kafka-3-more-metrics
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              containerPort: 9095
              name: monitoring
          env:
            - name: KAFKA_SERVERS
              value: "kafka-svc.kafka-kraft.svc.cluster.local:9092"
            - name: MESSAGES_AMOUNT
              value: "10000000"
            - name: TOPIC
              value: 3-partition
      restartPolicy: OnFailure
      # The pod template ends here
