apiVersion: batch/v1
kind: Job
metadata:
  name: alpakka-kafka-publisher-1-million
spec:
  template:
    # This is the pod template
    spec:
      containers:
        - name: alpakka-kafka-publisher-1-million
          image: miguelemos/alpakka_kafka_publisher:amd64
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_SERVERS
              value: "kafka-svc.kafka-kraft.svc.cluster.local:9092"
            - name: MESSAGES_AMOUNT
              value: "26000000"
            - name: TOPIC
              value: 3-partition
      restartPolicy: OnFailure
      # The pod template ends here
