# first run kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alpakka-monitor
  labels:
    app: alpakka
spec:
  selector:
    matchLabels:
      app: alpakka
  endpoints:
    - port: monitoring
      interval: 10s
      honorLabels: true
      path: /