apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  labels:
    app: pcs-cluster
spec:
  containers:
    - name: alpakka-kafka-publisher-1-million
      image: miguelemos/alpakka_kafka_publisher:with-prometheus-and-service-monitor
      imagePullPolicy: IfNotPresent
      ports:
        - protocol: TCP
          containerPort: 9095
          name: monitoring
      env:
        - name: KAFKA_SERVERS
          value: "kafka-svc.kafka-kraft.svc.cluster.local:9092"
        - name: MESSAGES_AMOUNT
          value: "26000000"
        - name: TOPIC
          value: 3-partition
  restartPolicy: Always
